title: "Tiago Nunes"
description: "Tracking my InfoSec journey."
baseurl: ""
url: "https://tiagomanunes.github.io"

collections:
  writeups:
    output: true
    permalink: /writeups/:title/
    sort_by: date

defaults:
  - scope:
      path: ""
      type: writeups
    values:
      layout: "post"

